[tool.poetry]
name = "multipass_examples"
version = "0.1.0"
description = "Pangea Multipass authorization library examples"
authors = ["Apurv Jawle <apurv.jawle@pangea.cloud>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pangea-sdk = "^5.1.0"
pangea-multipass = { path = "../../packages/pangea-multipass", develop = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
