.base:
  image: python:3.10
  before_script:
    - !reference [.setup, update-pip]
    - !reference [.setup, update-poetry]

    - cd pangea_multipass_lib/pangea-multipass
    - poetry check --lock
    - poetry install
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

build:
  extends: .base
  stage: build
  script:
    - poetry build
  artifacts:
    paths: ["pangea_multipass_lib/pangea-multipass/dist"]
    when: on_success

publish:
  extends: .base
  stage: publish
  needs: [build]
  script:
    - bash ../../dev/validate_tag.sh $CI_COMMIT_TAG
    - poetry publish --username __token__ --password $PYPI_SDK_TOKEN
  rules:
    - if: $CI_COMMIT_TAG =~ /pangea-multipass\/.+/
