.base-multipass:
  image: python:3.10@sha256:0a886c151ca7a5deffce7ec5c8b519e75cf238274232119d9d791dc22b0d0fd3
  before_script:
    - !reference [.setup, update-pip]
    - !reference [.setup, update-poetry]

    - cd packages/pangea-multipass
    - poetry check --lock
    - poetry install
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

build-multipass:
  extends: .base-multipass
  needs: []
  script:
    - poetry build
  artifacts:
    paths: ["packages/pangea-multipass/dist"]
    when: on_success

publish-multipass:
  extends: .base-multipass
  needs: [build-multipass]
  script:
    - bash ../../dev/validate_tag.sh $CI_COMMIT_TAG
    - poetry publish --username __token__ --password $PYPI_SDK_TOKEN
  rules:
    - if: $CI_COMMIT_TAG =~ /pangea-multipass\/.+/

.multipass-test-base:
  image: python:3.10@sha256:0a886c151ca7a5deffce7ec5c8b519e75cf238274232119d9d791dc22b0d0fd3
  before_script:
    - !reference [.setup, update-pip]
    - !reference [.setup, update-poetry]

    - cd packages/pangea-multipass
    - poetry check --lock
    - poetry install
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

multipass-integration-tests:
  extends: .multipass-test-base
  needs: [build-multipass]
  script:
    - poetry run python -m unittest tests.integration
