.base-langchain:
  image: python:3.12@sha256:089e151d3de18a20f08367ac60ff93c63372dca78c63cbaca70ddfde8761f34f
  before_script:
    - !reference [.setup, update-pip]
    - !reference [.setup, update-poetry]

    - cd packages/pangea-multipass-langchain
    - poetry check --lock
    - poetry install
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

build-langchain:
  extends: .base-langchain
  needs: []
  script:
    - poetry build
  artifacts:
    paths: ["packages/pangea-multipass-langchain/dist"]
    when: on_success

publish-langchain:
  extends: .base-langchain
  needs: [build-langchain]
  script:
    - bash ../../dev/validate_tag.sh $CI_COMMIT_TAG
    - poetry publish --username __token__ --password $PYPI_SDK_TOKEN
  rules:
    - if: $CI_COMMIT_TAG =~ /pangea-multipass-langchain\/.+/
