[project]
name = "pangea-multipass-langchain"
version = "0.2.0"
description = "Pangea Multipass authorization library for LangChain"
authors = [
    { name = "Apurv Jawle", email = "apurv.jawle@pangea.cloud" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "langchain (==0.3.25)",
    "pangea-multipass (>=0.2.0)",
]

[tool.poetry]
packages = [
    { include = "pangea_multipass_langchain" }
]

[tool.poetry.dependencies]
pangea-multipass = { path = "../pangea-multipass", develop = true }

[tool.poetry.group.dev.dependencies]
mypy = "1.16.0"

[[tool.mypy.overrides]]
module = ["pangea_multipass.*"]
follow_untyped_imports = true

[build-system]
requires = ["poetry-core>=1.9.1"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
src_paths = ["pangea_multipass_langchain", "tests"]
known_local_folder = ["pangea_multipass_langchain", "tests"]

[tool.mypy]
python_version = "3.10"
color_output = true
error_summary = true
pretty = true
show_column_numbers = true
warn_unused_ignores = true
