[project]
name = "pangea-multipass-langchain"
version = "0.2.0"
description = "Pangea Multipass authorization library for LangChain"
authors = [
    { name = "Apurv Jawle", email = "apurv.jawle@pangea.cloud" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "langchain (==0.3.26)",
    "pangea-multipass (>=0.2.0)",
]

[dependency-groups]
dev = [
    "mypy==1.16.1",
]

[tool.uv.sources]
pangea-multipass = { path = "../pangea-multipass", editable = true }

[build-system]
requires = ["hatchling==1.27.0"]
build-backend = "hatchling.build"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
src_paths = ["pangea_multipass_langchain", "tests"]
known_local_folder = ["pangea_multipass_langchain", "tests"]

[tool.mypy]
python_version = "3.10"
color_output = true
error_summary = true
pretty = true
show_column_numbers = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["pangea_multipass.*"]
follow_untyped_imports = true
