[project]
name = "langchain_examples"
version = "0.1.0"
description = "Pangea Multipass authorization library for LangChain"
authors = [
    { name = "Apurv Jawle", email = "apurv.jawle@pangea.cloud" }
]
license = "MIT"
package-mode = false
requires-python = ">=3.10,<3.13"
dependencies = [
    "pangea-multipass-langchain (>=0.2.0)",
    "pangea-multipass (>=0.2.0)",
    "google-api-python-client (>=2.151.0)",
    "google-auth-httplib2 (>=0.2.0)",
    "langchain-google-community (>=2.0.2)",
    "lxml (>=5.3.0)",
    "faiss-cpu (>=1.9.0)",
    "boto3 (>=1.36.22,<2.0.0)",
]

[tool.poetry.dependencies]
pangea-multipass-langchain = { path = "../../packages/pangea-multipass-langchain", develop = true }
pangea-multipass = { path = "../../packages/pangea-multipass", develop = true }

[tool.poetry.group.dev.dependencies]
mypy = "1.14.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
line_length = 120
